[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx vite build"]

[start]
cmd = "npx serve -s dist -l $PORT"

[variables]
NODE_ENV = "production"
