[build]
builder = "RAILPACK"
watchPatterns = ["**"]

[[build.env]]
key = "NODE_ENV"
value = "development"

[deploy]
startCommand = "ls -la apps/api/ && ls -la apps/api/dist/ && cd packages/database && npx prisma migrate deploy && cd ../.. && npm run start -w apps/api"
