[build]
builder = "nixpacks"
nixpacksVersion = "1.38.0"

[build.nixpacksPlan]
phases = ["setup", "install", "build"]

[build.nixpacksPlan.setup]
nixPkgs = ["nodejs_20", "npm"]

[build.nixpacksPlan.install]
cmds = ["npm ci"]

[build.nixpacksPlan.build]
cmds = [
  "npm run prisma:generate -w packages/database",
  "npm run build -w packages/database",
  "npm run build -w packages/types",
  "npm run build -w apps/api"
]

[deploy]
startCommand = "cd apps/api && npx prisma migrate deploy --schema ../../packages/database/prisma/schema.prisma && cd ../.. && npm run start -w apps/api"
