[build]
builder = "RAILPACK"
watchPatterns = ["**"]

[build.railpackBuild]
buildCommand = "npm run prisma:generate -w packages/database && npm run build -w packages/database && npm run build -w packages/types && npm run build -w apps/api"

[deploy]
startCommand = "cd apps/api && npx prisma migrate deploy --schema ../../packages/database/prisma/schema.prisma && cd ../.. && npm run start -w apps/api"
