[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run prisma:generate -w packages/database", "npm run build"]

[start]
cmd = "npx prisma migrate deploy && npm start"
