[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build -w packages/database", "npx prisma generate", "npm run build"]

[start]
cmd = "npx prisma migrate deploy && npm start"
